/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAbandonedCartsRouteImport } from './routes/_authenticated/admin/abandoned-carts'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminBackInStockRouteImport } from './routes/_authenticated/admin/back-in-stock'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminDiscountsRouteImport } from './routes/_authenticated/admin/discounts'
import { Route as AuthenticatedAdminEarlyAccessRouteImport } from './routes/_authenticated/admin/early-access'
import { Route as AuthenticatedAdminEmailTemplatesRouteImport } from './routes/_authenticated/admin/email-templates'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductDropsRouteImport } from './routes/_authenticated/admin/product-drops'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin/promotions'
import { Route as AuthenticatedAdminPurchaseOrdersRouteImport } from './routes/_authenticated/admin/purchase-orders'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin/refunds'
import { Route as AuthenticatedAdminReturnsRouteImport } from './routes/_authenticated/admin/returns'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminWarehousesRouteImport } from './routes/_authenticated/admin/warehouses'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as AuthenticatedAdminWishlistsRouteImport } from './routes/_authenticated/admin/wishlists'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicSliceWebhookRouteImport } from './routes/api/public/slice-webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AuthenticatedAdminAnalyticsIndexRouteImport } from './routes/_authenticated/admin/analytics/index'
import { Route as AuthenticatedAdminAnalyticsCustomersRouteImport } from './routes/_authenticated/admin/analytics/customers'
import { Route as AuthenticatedAdminAnalyticsDayOfWeekRouteImport } from './routes/_authenticated/admin/analytics/day-of-week'
import { Route as AuthenticatedAdminAnalyticsFinancialRouteImport } from './routes/_authenticated/admin/analytics/financial'
import { Route as AuthenticatedAdminAnalyticsGeographicRouteImport } from './routes/_authenticated/admin/analytics/geographic'
import { Route as AuthenticatedAdminAnalyticsProductsRouteImport } from './routes/_authenticated/admin/analytics/products'
import { Route as AuthenticatedAdminAnalyticsReportsRouteImport } from './routes/_authenticated/admin/analytics/reports'
import { Route as AuthenticatedAdminAnalyticsSalesRouteImport } from './routes/_authenticated/admin/analytics/sales'
import { Route as AuthenticatedAdminCmsAnnouncementsRouteImport } from './routes/_authenticated/admin/cms/announcements'
import { Route as AuthenticatedAdminCmsFaqRouteImport } from './routes/_authenticated/admin/cms/faq'
import { Route as AuthenticatedAdminCmsHomepageRouteImport } from './routes/_authenticated/admin/cms/homepage'
import { Route as AuthenticatedAdminCmsJournalRouteImport } from './routes/_authenticated/admin/cms/journal'
import { Route as AuthenticatedAdminCmsMediaRouteImport } from './routes/_authenticated/admin/cms/media'
import { Route as AuthenticatedAdminCmsNavigationRouteImport } from './routes/_authenticated/admin/cms/navigation'
import { Route as AuthenticatedAdminCmsPagesRouteImport } from './routes/_authenticated/admin/cms/pages'
import { Route as AuthenticatedAdminSeoIndexRouteImport } from './routes/_authenticated/admin/seo/index'
import { Route as AuthenticatedAdminSeoRedirectsRouteImport } from './routes/_authenticated/admin/seo/redirects'
import { Route as AuthenticatedAdminSeoSearchAnalyticsRouteImport } from './routes/_authenticated/admin/seo/search-analytics'
import { Route as ApiPublicV1SplatRouteImport } from './routes/api/public/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAbandonedCartsRoute =
  AuthenticatedAdminAbandonedCartsRouteImport.update({
    id: '/abandoned-carts',
    path: '/abandoned-carts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackInStockRoute =
  AuthenticatedAdminBackInStockRouteImport.update({
    id: '/back-in-stock',
    path: '/back-in-stock',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiscountsRoute =
  AuthenticatedAdminDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEarlyAccessRoute =
  AuthenticatedAdminEarlyAccessRouteImport.update({
    id: '/early-access',
    path: '/early-access',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailTemplatesRoute =
  AuthenticatedAdminEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductDropsRoute =
  AuthenticatedAdminProductDropsRouteImport.update({
    id: '/product-drops',
    path: '/product-drops',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchaseOrdersRoute =
  AuthenticatedAdminPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/refunds',
    path: '/refunds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReturnsRoute =
  AuthenticatedAdminReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWarehousesRoute =
  AuthenticatedAdminWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWishlistsRoute =
  AuthenticatedAdminWishlistsRouteImport.update({
    id: '/wishlists',
    path: '/wishlists',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSliceWebhookRoute = ApiPublicSliceWebhookRouteImport.update({
  id: '/api/public/slice-webhook',
  path: '/api/public/slice-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsIndexRoute =
  AuthenticatedAdminAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsCustomersRoute =
  AuthenticatedAdminAnalyticsCustomersRouteImport.update({
    id: '/analytics/customers',
    path: '/analytics/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsDayOfWeekRoute =
  AuthenticatedAdminAnalyticsDayOfWeekRouteImport.update({
    id: '/analytics/day-of-week',
    path: '/analytics/day-of-week',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsFinancialRoute =
  AuthenticatedAdminAnalyticsFinancialRouteImport.update({
    id: '/analytics/financial',
    path: '/analytics/financial',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsGeographicRoute =
  AuthenticatedAdminAnalyticsGeographicRouteImport.update({
    id: '/analytics/geographic',
    path: '/analytics/geographic',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsProductsRoute =
  AuthenticatedAdminAnalyticsProductsRouteImport.update({
    id: '/analytics/products',
    path: '/analytics/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsReportsRoute =
  AuthenticatedAdminAnalyticsReportsRouteImport.update({
    id: '/analytics/reports',
    path: '/analytics/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsSalesRoute =
  AuthenticatedAdminAnalyticsSalesRouteImport.update({
    id: '/analytics/sales',
    path: '/analytics/sales',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsAnnouncementsRoute =
  AuthenticatedAdminCmsAnnouncementsRouteImport.update({
    id: '/cms/announcements',
    path: '/cms/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsFaqRoute =
  AuthenticatedAdminCmsFaqRouteImport.update({
    id: '/cms/faq',
    path: '/cms/faq',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsHomepageRoute =
  AuthenticatedAdminCmsHomepageRouteImport.update({
    id: '/cms/homepage',
    path: '/cms/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsJournalRoute =
  AuthenticatedAdminCmsJournalRouteImport.update({
    id: '/cms/journal',
    path: '/cms/journal',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsMediaRoute =
  AuthenticatedAdminCmsMediaRouteImport.update({
    id: '/cms/media',
    path: '/cms/media',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsNavigationRoute =
  AuthenticatedAdminCmsNavigationRouteImport.update({
    id: '/cms/navigation',
    path: '/cms/navigation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCmsPagesRoute =
  AuthenticatedAdminCmsPagesRouteImport.update({
    id: '/cms/pages',
    path: '/cms/pages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoIndexRoute =
  AuthenticatedAdminSeoIndexRouteImport.update({
    id: '/seo/',
    path: '/seo/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoRedirectsRoute =
  AuthenticatedAdminSeoRedirectsRouteImport.update({
    id: '/seo/redirects',
    path: '/seo/redirects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoSearchAnalyticsRoute =
  AuthenticatedAdminSeoSearchAnalyticsRouteImport.update({
    id: '/seo/search-analytics',
    path: '/seo/search-analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicV1SplatRoute = ApiPublicV1SplatRouteImport.update({
  id: '/api/public/v1/$',
  path: '/api/public/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/abandoned-carts': typeof AuthenticatedAdminAbandonedCartsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/back-in-stock': typeof AuthenticatedAdminBackInStockRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/admin/early-access': typeof AuthenticatedAdminEarlyAccessRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/product-drops': typeof AuthenticatedAdminProductDropsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/returns': typeof AuthenticatedAdminReturnsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/wishlists': typeof AuthenticatedAdminWishlistsRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/slice-webhook': typeof ApiPublicSliceWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/analytics/customers': typeof AuthenticatedAdminAnalyticsCustomersRoute
  '/admin/analytics/day-of-week': typeof AuthenticatedAdminAnalyticsDayOfWeekRoute
  '/admin/analytics/financial': typeof AuthenticatedAdminAnalyticsFinancialRoute
  '/admin/analytics/geographic': typeof AuthenticatedAdminAnalyticsGeographicRoute
  '/admin/analytics/products': typeof AuthenticatedAdminAnalyticsProductsRoute
  '/admin/analytics/reports': typeof AuthenticatedAdminAnalyticsReportsRoute
  '/admin/analytics/sales': typeof AuthenticatedAdminAnalyticsSalesRoute
  '/admin/cms/announcements': typeof AuthenticatedAdminCmsAnnouncementsRoute
  '/admin/cms/faq': typeof AuthenticatedAdminCmsFaqRoute
  '/admin/cms/homepage': typeof AuthenticatedAdminCmsHomepageRoute
  '/admin/cms/journal': typeof AuthenticatedAdminCmsJournalRoute
  '/admin/cms/media': typeof AuthenticatedAdminCmsMediaRoute
  '/admin/cms/navigation': typeof AuthenticatedAdminCmsNavigationRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/admin/seo/redirects': typeof AuthenticatedAdminSeoRedirectsRoute
  '/admin/seo/search-analytics': typeof AuthenticatedAdminSeoSearchAnalyticsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/admin/analytics/': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/admin/seo/': typeof AuthenticatedAdminSeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/abandoned-carts': typeof AuthenticatedAdminAbandonedCartsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/back-in-stock': typeof AuthenticatedAdminBackInStockRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/admin/early-access': typeof AuthenticatedAdminEarlyAccessRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/product-drops': typeof AuthenticatedAdminProductDropsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/returns': typeof AuthenticatedAdminReturnsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/wishlists': typeof AuthenticatedAdminWishlistsRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/slice-webhook': typeof ApiPublicSliceWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/analytics/customers': typeof AuthenticatedAdminAnalyticsCustomersRoute
  '/admin/analytics/day-of-week': typeof AuthenticatedAdminAnalyticsDayOfWeekRoute
  '/admin/analytics/financial': typeof AuthenticatedAdminAnalyticsFinancialRoute
  '/admin/analytics/geographic': typeof AuthenticatedAdminAnalyticsGeographicRoute
  '/admin/analytics/products': typeof AuthenticatedAdminAnalyticsProductsRoute
  '/admin/analytics/reports': typeof AuthenticatedAdminAnalyticsReportsRoute
  '/admin/analytics/sales': typeof AuthenticatedAdminAnalyticsSalesRoute
  '/admin/cms/announcements': typeof AuthenticatedAdminCmsAnnouncementsRoute
  '/admin/cms/faq': typeof AuthenticatedAdminCmsFaqRoute
  '/admin/cms/homepage': typeof AuthenticatedAdminCmsHomepageRoute
  '/admin/cms/journal': typeof AuthenticatedAdminCmsJournalRoute
  '/admin/cms/media': typeof AuthenticatedAdminCmsMediaRoute
  '/admin/cms/navigation': typeof AuthenticatedAdminCmsNavigationRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/admin/seo/redirects': typeof AuthenticatedAdminSeoRedirectsRoute
  '/admin/seo/search-analytics': typeof AuthenticatedAdminSeoSearchAnalyticsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/admin/seo': typeof AuthenticatedAdminSeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/_authenticated/admin/abandoned-carts': typeof AuthenticatedAdminAbandonedCartsRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/back-in-stock': typeof AuthenticatedAdminBackInStockRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/_authenticated/admin/early-access': typeof AuthenticatedAdminEarlyAccessRoute
  '/_authenticated/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/product-drops': typeof AuthenticatedAdminProductDropsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/purchase-orders': typeof AuthenticatedAdminPurchaseOrdersRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/returns': typeof AuthenticatedAdminReturnsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/warehouses': typeof AuthenticatedAdminWarehousesRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/admin/wishlists': typeof AuthenticatedAdminWishlistsRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/slice-webhook': typeof ApiPublicSliceWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/analytics/customers': typeof AuthenticatedAdminAnalyticsCustomersRoute
  '/_authenticated/admin/analytics/day-of-week': typeof AuthenticatedAdminAnalyticsDayOfWeekRoute
  '/_authenticated/admin/analytics/financial': typeof AuthenticatedAdminAnalyticsFinancialRoute
  '/_authenticated/admin/analytics/geographic': typeof AuthenticatedAdminAnalyticsGeographicRoute
  '/_authenticated/admin/analytics/products': typeof AuthenticatedAdminAnalyticsProductsRoute
  '/_authenticated/admin/analytics/reports': typeof AuthenticatedAdminAnalyticsReportsRoute
  '/_authenticated/admin/analytics/sales': typeof AuthenticatedAdminAnalyticsSalesRoute
  '/_authenticated/admin/cms/announcements': typeof AuthenticatedAdminCmsAnnouncementsRoute
  '/_authenticated/admin/cms/faq': typeof AuthenticatedAdminCmsFaqRoute
  '/_authenticated/admin/cms/homepage': typeof AuthenticatedAdminCmsHomepageRoute
  '/_authenticated/admin/cms/journal': typeof AuthenticatedAdminCmsJournalRoute
  '/_authenticated/admin/cms/media': typeof AuthenticatedAdminCmsMediaRoute
  '/_authenticated/admin/cms/navigation': typeof AuthenticatedAdminCmsNavigationRoute
  '/_authenticated/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRoute
  '/_authenticated/admin/seo/redirects': typeof AuthenticatedAdminSeoRedirectsRoute
  '/_authenticated/admin/seo/search-analytics': typeof AuthenticatedAdminSeoSearchAnalyticsRoute
  '/api/public/v1/$': typeof ApiPublicV1SplatRoute
  '/_authenticated/admin/analytics/': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/_authenticated/admin/seo/': typeof AuthenticatedAdminSeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/admin/abandoned-carts'
    | '/admin/audit-log'
    | '/admin/back-in-stock'
    | '/admin/campaigns'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/early-access'
    | '/admin/email-templates'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/product-drops'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/purchase-orders'
    | '/admin/refunds'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/warehouses'
    | '/admin/webhooks'
    | '/admin/wishlists'
    | '/api/public/checkout'
    | '/api/public/razorpay-webhook'
    | '/api/public/slice-webhook'
    | '/api/public/stripe-webhook'
    | '/api/v1/$'
    | '/admin/'
    | '/admin/analytics/customers'
    | '/admin/analytics/day-of-week'
    | '/admin/analytics/financial'
    | '/admin/analytics/geographic'
    | '/admin/analytics/products'
    | '/admin/analytics/reports'
    | '/admin/analytics/sales'
    | '/admin/cms/announcements'
    | '/admin/cms/faq'
    | '/admin/cms/homepage'
    | '/admin/cms/journal'
    | '/admin/cms/media'
    | '/admin/cms/navigation'
    | '/admin/cms/pages'
    | '/admin/seo/redirects'
    | '/admin/seo/search-analytics'
    | '/api/public/v1/$'
    | '/admin/analytics/'
    | '/admin/seo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/admin/abandoned-carts'
    | '/admin/audit-log'
    | '/admin/back-in-stock'
    | '/admin/campaigns'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/early-access'
    | '/admin/email-templates'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/product-drops'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/purchase-orders'
    | '/admin/refunds'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/warehouses'
    | '/admin/webhooks'
    | '/admin/wishlists'
    | '/api/public/checkout'
    | '/api/public/razorpay-webhook'
    | '/api/public/slice-webhook'
    | '/api/public/stripe-webhook'
    | '/api/v1/$'
    | '/admin'
    | '/admin/analytics/customers'
    | '/admin/analytics/day-of-week'
    | '/admin/analytics/financial'
    | '/admin/analytics/geographic'
    | '/admin/analytics/products'
    | '/admin/analytics/reports'
    | '/admin/analytics/sales'
    | '/admin/cms/announcements'
    | '/admin/cms/faq'
    | '/admin/cms/homepage'
    | '/admin/cms/journal'
    | '/admin/cms/media'
    | '/admin/cms/navigation'
    | '/admin/cms/pages'
    | '/admin/seo/redirects'
    | '/admin/seo/search-analytics'
    | '/api/public/v1/$'
    | '/admin/analytics'
    | '/admin/seo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/_authenticated/admin/abandoned-carts'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/back-in-stock'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/discounts'
    | '/_authenticated/admin/early-access'
    | '/_authenticated/admin/email-templates'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/product-drops'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/purchase-orders'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/returns'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/warehouses'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/admin/wishlists'
    | '/api/public/checkout'
    | '/api/public/razorpay-webhook'
    | '/api/public/slice-webhook'
    | '/api/public/stripe-webhook'
    | '/api/v1/$'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/analytics/customers'
    | '/_authenticated/admin/analytics/day-of-week'
    | '/_authenticated/admin/analytics/financial'
    | '/_authenticated/admin/analytics/geographic'
    | '/_authenticated/admin/analytics/products'
    | '/_authenticated/admin/analytics/reports'
    | '/_authenticated/admin/analytics/sales'
    | '/_authenticated/admin/cms/announcements'
    | '/_authenticated/admin/cms/faq'
    | '/_authenticated/admin/cms/homepage'
    | '/_authenticated/admin/cms/journal'
    | '/_authenticated/admin/cms/media'
    | '/_authenticated/admin/cms/navigation'
    | '/_authenticated/admin/cms/pages'
    | '/_authenticated/admin/seo/redirects'
    | '/_authenticated/admin/seo/search-analytics'
    | '/api/public/v1/$'
    | '/_authenticated/admin/analytics/'
    | '/_authenticated/admin/seo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicSliceWebhookRoute: typeof ApiPublicSliceWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicV1SplatRoute: typeof ApiPublicV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/abandoned-carts': {
      id: '/_authenticated/admin/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/admin/abandoned-carts'
      preLoaderRoute: typeof AuthenticatedAdminAbandonedCartsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/back-in-stock': {
      id: '/_authenticated/admin/back-in-stock'
      path: '/back-in-stock'
      fullPath: '/admin/back-in-stock'
      preLoaderRoute: typeof AuthenticatedAdminBackInStockRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/discounts': {
      id: '/_authenticated/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AuthenticatedAdminDiscountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/early-access': {
      id: '/_authenticated/admin/early-access'
      path: '/early-access'
      fullPath: '/admin/early-access'
      preLoaderRoute: typeof AuthenticatedAdminEarlyAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email-templates': {
      id: '/_authenticated/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/product-drops': {
      id: '/_authenticated/admin/product-drops'
      path: '/product-drops'
      fullPath: '/admin/product-drops'
      preLoaderRoute: typeof AuthenticatedAdminProductDropsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchase-orders': {
      id: '/_authenticated/admin/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AuthenticatedAdminPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/returns': {
      id: '/_authenticated/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AuthenticatedAdminReturnsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/warehouses': {
      id: '/_authenticated/admin/warehouses'
      path: '/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AuthenticatedAdminWarehousesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/wishlists': {
      id: '/_authenticated/admin/wishlists'
      path: '/wishlists'
      fullPath: '/admin/wishlists'
      preLoaderRoute: typeof AuthenticatedAdminWishlistsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slice-webhook': {
      id: '/api/public/slice-webhook'
      path: '/api/public/slice-webhook'
      fullPath: '/api/public/slice-webhook'
      preLoaderRoute: typeof ApiPublicSliceWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics/': {
      id: '/_authenticated/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/customers': {
      id: '/_authenticated/admin/analytics/customers'
      path: '/analytics/customers'
      fullPath: '/admin/analytics/customers'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/day-of-week': {
      id: '/_authenticated/admin/analytics/day-of-week'
      path: '/analytics/day-of-week'
      fullPath: '/admin/analytics/day-of-week'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsDayOfWeekRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/financial': {
      id: '/_authenticated/admin/analytics/financial'
      path: '/analytics/financial'
      fullPath: '/admin/analytics/financial'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsFinancialRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/geographic': {
      id: '/_authenticated/admin/analytics/geographic'
      path: '/analytics/geographic'
      fullPath: '/admin/analytics/geographic'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsGeographicRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/products': {
      id: '/_authenticated/admin/analytics/products'
      path: '/analytics/products'
      fullPath: '/admin/analytics/products'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/reports': {
      id: '/_authenticated/admin/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/admin/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics/sales': {
      id: '/_authenticated/admin/analytics/sales'
      path: '/analytics/sales'
      fullPath: '/admin/analytics/sales'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/announcements': {
      id: '/_authenticated/admin/cms/announcements'
      path: '/cms/announcements'
      fullPath: '/admin/cms/announcements'
      preLoaderRoute: typeof AuthenticatedAdminCmsAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/faq': {
      id: '/_authenticated/admin/cms/faq'
      path: '/cms/faq'
      fullPath: '/admin/cms/faq'
      preLoaderRoute: typeof AuthenticatedAdminCmsFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/homepage': {
      id: '/_authenticated/admin/cms/homepage'
      path: '/cms/homepage'
      fullPath: '/admin/cms/homepage'
      preLoaderRoute: typeof AuthenticatedAdminCmsHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/journal': {
      id: '/_authenticated/admin/cms/journal'
      path: '/cms/journal'
      fullPath: '/admin/cms/journal'
      preLoaderRoute: typeof AuthenticatedAdminCmsJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/media': {
      id: '/_authenticated/admin/cms/media'
      path: '/cms/media'
      fullPath: '/admin/cms/media'
      preLoaderRoute: typeof AuthenticatedAdminCmsMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/navigation': {
      id: '/_authenticated/admin/cms/navigation'
      path: '/cms/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AuthenticatedAdminCmsNavigationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cms/pages': {
      id: '/_authenticated/admin/cms/pages'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AuthenticatedAdminCmsPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo/': {
      id: '/_authenticated/admin/seo/'
      path: '/seo'
      fullPath: '/admin/seo/'
      preLoaderRoute: typeof AuthenticatedAdminSeoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo/redirects': {
      id: '/_authenticated/admin/seo/redirects'
      path: '/seo/redirects'
      fullPath: '/admin/seo/redirects'
      preLoaderRoute: typeof AuthenticatedAdminSeoRedirectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo/search-analytics': {
      id: '/_authenticated/admin/seo/search-analytics'
      path: '/seo/search-analytics'
      fullPath: '/admin/seo/search-analytics'
      preLoaderRoute: typeof AuthenticatedAdminSeoSearchAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/v1/$': {
      id: '/api/public/v1/$'
      path: '/api/public/v1/$'
      fullPath: '/api/public/v1/$'
      preLoaderRoute: typeof ApiPublicV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAbandonedCartsRoute: typeof AuthenticatedAdminAbandonedCartsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBackInStockRoute: typeof AuthenticatedAdminBackInStockRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDiscountsRoute: typeof AuthenticatedAdminDiscountsRoute
  AuthenticatedAdminEarlyAccessRoute: typeof AuthenticatedAdminEarlyAccessRoute
  AuthenticatedAdminEmailTemplatesRoute: typeof AuthenticatedAdminEmailTemplatesRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductDropsRoute: typeof AuthenticatedAdminProductDropsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminPurchaseOrdersRoute: typeof AuthenticatedAdminPurchaseOrdersRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminReturnsRoute: typeof AuthenticatedAdminReturnsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminWarehousesRoute: typeof AuthenticatedAdminWarehousesRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminWishlistsRoute: typeof AuthenticatedAdminWishlistsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAnalyticsCustomersRoute: typeof AuthenticatedAdminAnalyticsCustomersRoute
  AuthenticatedAdminAnalyticsDayOfWeekRoute: typeof AuthenticatedAdminAnalyticsDayOfWeekRoute
  AuthenticatedAdminAnalyticsFinancialRoute: typeof AuthenticatedAdminAnalyticsFinancialRoute
  AuthenticatedAdminAnalyticsGeographicRoute: typeof AuthenticatedAdminAnalyticsGeographicRoute
  AuthenticatedAdminAnalyticsProductsRoute: typeof AuthenticatedAdminAnalyticsProductsRoute
  AuthenticatedAdminAnalyticsReportsRoute: typeof AuthenticatedAdminAnalyticsReportsRoute
  AuthenticatedAdminAnalyticsSalesRoute: typeof AuthenticatedAdminAnalyticsSalesRoute
  AuthenticatedAdminCmsAnnouncementsRoute: typeof AuthenticatedAdminCmsAnnouncementsRoute
  AuthenticatedAdminCmsFaqRoute: typeof AuthenticatedAdminCmsFaqRoute
  AuthenticatedAdminCmsHomepageRoute: typeof AuthenticatedAdminCmsHomepageRoute
  AuthenticatedAdminCmsJournalRoute: typeof AuthenticatedAdminCmsJournalRoute
  AuthenticatedAdminCmsMediaRoute: typeof AuthenticatedAdminCmsMediaRoute
  AuthenticatedAdminCmsNavigationRoute: typeof AuthenticatedAdminCmsNavigationRoute
  AuthenticatedAdminCmsPagesRoute: typeof AuthenticatedAdminCmsPagesRoute
  AuthenticatedAdminSeoRedirectsRoute: typeof AuthenticatedAdminSeoRedirectsRoute
  AuthenticatedAdminSeoSearchAnalyticsRoute: typeof AuthenticatedAdminSeoSearchAnalyticsRoute
  AuthenticatedAdminAnalyticsIndexRoute: typeof AuthenticatedAdminAnalyticsIndexRoute
  AuthenticatedAdminSeoIndexRoute: typeof AuthenticatedAdminSeoIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAbandonedCartsRoute:
      AuthenticatedAdminAbandonedCartsRoute,
    AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
    AuthenticatedAdminBackInStockRoute: AuthenticatedAdminBackInStockRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminDiscountsRoute: AuthenticatedAdminDiscountsRoute,
    AuthenticatedAdminEarlyAccessRoute: AuthenticatedAdminEarlyAccessRoute,
    AuthenticatedAdminEmailTemplatesRoute:
      AuthenticatedAdminEmailTemplatesRoute,
    AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminProductDropsRoute: AuthenticatedAdminProductDropsRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
    AuthenticatedAdminPurchaseOrdersRoute:
      AuthenticatedAdminPurchaseOrdersRoute,
    AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
    AuthenticatedAdminReturnsRoute: AuthenticatedAdminReturnsRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminWarehousesRoute: AuthenticatedAdminWarehousesRoute,
    AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
    AuthenticatedAdminWishlistsRoute: AuthenticatedAdminWishlistsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminAnalyticsCustomersRoute:
      AuthenticatedAdminAnalyticsCustomersRoute,
    AuthenticatedAdminAnalyticsDayOfWeekRoute:
      AuthenticatedAdminAnalyticsDayOfWeekRoute,
    AuthenticatedAdminAnalyticsFinancialRoute:
      AuthenticatedAdminAnalyticsFinancialRoute,
    AuthenticatedAdminAnalyticsGeographicRoute:
      AuthenticatedAdminAnalyticsGeographicRoute,
    AuthenticatedAdminAnalyticsProductsRoute:
      AuthenticatedAdminAnalyticsProductsRoute,
    AuthenticatedAdminAnalyticsReportsRoute:
      AuthenticatedAdminAnalyticsReportsRoute,
    AuthenticatedAdminAnalyticsSalesRoute:
      AuthenticatedAdminAnalyticsSalesRoute,
    AuthenticatedAdminCmsAnnouncementsRoute:
      AuthenticatedAdminCmsAnnouncementsRoute,
    AuthenticatedAdminCmsFaqRoute: AuthenticatedAdminCmsFaqRoute,
    AuthenticatedAdminCmsHomepageRoute: AuthenticatedAdminCmsHomepageRoute,
    AuthenticatedAdminCmsJournalRoute: AuthenticatedAdminCmsJournalRoute,
    AuthenticatedAdminCmsMediaRoute: AuthenticatedAdminCmsMediaRoute,
    AuthenticatedAdminCmsNavigationRoute: AuthenticatedAdminCmsNavigationRoute,
    AuthenticatedAdminCmsPagesRoute: AuthenticatedAdminCmsPagesRoute,
    AuthenticatedAdminSeoRedirectsRoute: AuthenticatedAdminSeoRedirectsRoute,
    AuthenticatedAdminSeoSearchAnalyticsRoute:
      AuthenticatedAdminSeoSearchAnalyticsRoute,
    AuthenticatedAdminAnalyticsIndexRoute:
      AuthenticatedAdminAnalyticsIndexRoute,
    AuthenticatedAdminSeoIndexRoute: AuthenticatedAdminSeoIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicSliceWebhookRoute: ApiPublicSliceWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicV1SplatRoute: ApiPublicV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
